export { default as Header } from './Header'
export { default as Readme } from './Readme'
export { default as LeftBottomOne } from './LeftBottomOne'
export { default as LeftBottomTwo } from './LeftBottomTwo'
export { default as BodyLeftTop } from './BodyLeftTop'
export { default as BodyLeftBottom } from './BodyLeftBottom'
export { default as BodyRightTop } from './BodyRightTop'
export { default as BodyRightTopTwo } from './BodyRightTopTwo'
export { default as BodyRightBottom } from './BodyRightBottom'
export { default as RightOne } from './RightOne'
export { default as RightPengLIng } from './RightPengLIng'
export { default as RightTwo } from './RightTwo'
export { default as RightFour } from './RightFour'
export { default as RightThree } from './RightThree'
 