server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /web
  
master:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zjtz?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    #IP白名单，可以访问数据监控 http://id:port/项目/druid/sql.html
    allow: 127.0.0.1
  enable: true

slave:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zjtz?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  enable: false
