DROP TABLE IF EXISTS zj_pxjh_week_plan;
CREATE TABLE  zj_pxjh_week_plan (
	plan_id	char(32) DEFAULT '' COMMENT '主键ID',
	oa_member_id	varchar(32) DEFAULT '' COMMENT '人员关联ID',
	plan_year	datetime DEFAULT NULL COMMENT '日程年限',
	plan_date	datetime DEFAULT NULL COMMENT '日程日期',
	plan_title	varchar(255) DEFAULT '' COMMENT '日程内容',
	plan_week	char(10) DEFAULT '' COMMENT '星期',
	week_num	varchar(500) DEFAULT '' COMMENT '周数',
	monday_train_content	varchar(500) DEFAULT '' COMMENT '星期一',
	tuesday_train_content	varchar(500) DEFAULT '' COMMENT '星期二',
	wednesday_train_content	varchar(500) DEFAULT '' COMMENT '星期三',
	thursday_train_content	varchar(500) DEFAULT '' COMMENT '星期四',
	friday_train_content	varchar(500) DEFAULT '' COMMENT '星期五',
	saturday_train_content	varchar(500) DEFAULT '' COMMENT '星期六',
	sunday_train_content	varchar(500) DEFAULT '' COMMENT '星期日',
	monday_meet_content	varchar(500) DEFAULT '' COMMENT '星期一',
	tuesday_meet_content	varchar(500) DEFAULT '' COMMENT '星期二',
	wednesday_meet_content	varchar(500) DEFAULT '' COMMENT '星期三',
	thursday_meet_content	varchar(500) DEFAULT '' COMMENT '星期四',
	friday_meet_content	varchar(500) DEFAULT '' COMMENT '星期五',
	saturday_meet_content	varchar(500) DEFAULT '' COMMENT '星期六',
	sunday_meet_content	varchar(500) DEFAULT '' COMMENT '星期日',
	monday_date	datetime DEFAULT NULL COMMENT '星期一日期',
	tuesday_date	datetime DEFAULT NULL COMMENT '星期二日期',
	wednesday_date	datetime DEFAULT NULL COMMENT '星期三日期',
	thursday_date	datetime DEFAULT NULL COMMENT '星期四日期',
	friday_date	datetime DEFAULT NULL COMMENT '星期五日期',
	saturday_date	datetime DEFAULT NULL COMMENT '星期六日期',
	sunday_date	datetime DEFAULT NULL COMMENT '星期日日期',
	del_flag	char(1) DEFAULT '' COMMENT '删除标识',
	create_time	datetime DEFAULT NULL COMMENT '创建时间',
	create_user	char(32) DEFAULT '' COMMENT '创建者',
	create_user_name	varchar(100) DEFAULT '' COMMENT '创建者姓名',
	modify_time	datetime DEFAULT NULL COMMENT '更新时间',
	modify_user	char(32) DEFAULT '' COMMENT '更新者',
	modify_user_name	varchar(100) DEFAULT '' COMMENT '更新者姓名',
PRIMARY KEY ( plan_id )
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='领导日程表';
